- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
<<<<<<< HEAD
      time: 27000 # 7.5 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 27000 # 7.5 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 27000 # 7.5 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 54000 # 15 hours
=======
      time: 36000 #10 hrs # Sunrise-RoleTime
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 #10 hrs # Sunrise-RoleTime
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 #10 hrs # Sunrise-RoleTime
    - !type:OverallPlaytimeRequirement
      time: 72000 #20 hrs # Sunrise-RoleTime
>>>>>>> 5775d4cdef (Merge sunrise build (#2))
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  radioBold: true
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  speciesBlacklist:
  - Vox

- type: startingGear
  id: CaptainGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  storage:
    back:
    - Flash
    - Telebaton
    # - StationCharter
