- type: job
  id: HeadOfSecurity
  name: job-name-hos
  description: job-description-hos
  playTimeTracker: JobHeadOfSecurity
  requirements:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 18000 #5 hrs # Sunrise-RoleTime
    - !type:DepartmentTimeRequirement
      department: Security
<<<<<<< HEAD
      time: 54000 # 15 hrs
    - !type:OverallPlaytimeRequirement
      time: 144000 #40 hrs
=======
      time: 54000 #15 hrs # Sunrise-RoleTime
>>>>>>> 5775d4cdef (Merge sunrise build (#2))
  weight: 10
  startingGear: HoSGear
  icon: "JobIconHeadOfSecurity"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  radioBold: true
  canBeAntag: false
  access:
  - HeadOfSecurity
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  speciesBlacklist:
  - Vox

- type: startingGear
  id: HoSGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: HoSPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltSecurity
<<<<<<< HEAD
    pocket1: WeaponPistolMk58
=======
    pocket1: WeaponPistolMk58Nonlethal # Sunrise-Edit
>>>>>>> fa59b6542d (Возврат нелетального оружия (#162))
  storage:
    back:
    - Flash
    - MagazinePistol
