- type: job
  id: SecurityCadet
  name: job-name-cadet
  description: job-description-cadet
  playTimeTracker: JobSecurityCadet
  requirements:
    - !type:OverallPlaytimeRequirement
<<<<<<< HEAD
      time: 9000 #2.5 hrs
=======
      time: 18000 #5 hrs # Sunrise-RoleTime
>>>>>>> 5775d4cdef (Merge sunrise build (#2))
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 #10 hrs # Sunrise-RoleTime
      inverted: true # stop playing intern if you're good at security!
  startingGear: SecurityCadetGear
  icon: "JobIconSecurityCadet"
  supervisors: job-supervisors-security
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  speciesBlacklist:
  - Vox

- type: startingGear
  id: SecurityCadetGear
  equipment:
<<<<<<< HEAD
    shoes: ClothingShoesBootsJackFilled
=======
    shoes: ClothingShoesBootsJackSec
>>>>>>> 5775d4cdef (Merge sunrise build (#2))
    outerClothing: ClothingOuterArmorBasic
    id: SecurityCadetPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
<<<<<<< HEAD
<<<<<<< HEAD
    pocket1: WeaponDisabler
    pocket2: BookSecurity
=======
    pocket1: HyperLinkBookCorporateLaw # Sunrise-edit
    pocket2: WeaponPistolMk58Nonlethal # Sunrise-Edit
>>>>>>> fa59b6542d (Возврат нелетального оружия (#162))
  storage:
    back:
    - Flash
    - Handcuffs
=======
    pocket1: WeaponPistolMk58
    pocket2: BookSecurity
>>>>>>> 5775d4cdef (Merge sunrise build (#2))
