- type: job
  id: Chef
  name: job-name-chef
  description: job-description-chef
  playTimeTracker: JobChef
  requirements:
<<<<<<< HEAD
    - !type:OverallPlaytimeRequirement
      time: 1800 # 30 Minutes
=======
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 3600 #1 hrs # Sunrise-RoleTime
>>>>>>> 5775d4cdef (Merge sunrise build (#2))
  startingGear: ChefGear
  icon: "JobIconChef"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Kitchen
  extendedAccess:
  - Hydroponics
  - Bar

- type: startingGear
  id: ChefGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: ChefPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltChefFilled
  #storage:
    #back:
    #- Stuff
