- type: antag
  id: Nukeops
  name: roles-antag-nuclear-operative-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5h
  guides: [ NuclearOperatives ]

- type: antag
  id: NukeopsMedic
  name: roles-antag-nuclear-operative-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-agent-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5h
  - !type:RoleTimeRequirement
    role: JobChemist
    time: 10800 # 3h
  guides: [ NuclearOperatives ]

- type: antag
  id: NukeopsCommander
  name: roles-antag-nuclear-operative-commander-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-commander-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 18000 # 5h
  - !type:DepartmentTimeRequirement
    department: Security
    time: 18000 # 5h
  # should be changed to nukie playtime when thats tracked (wyci)
  guides: [ NuclearOperatives ]

- type: startingGear
  id: SyndicateOperativeGearFullNoUplink
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicate
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudSyndicate
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
<<<<<<< HEAD
    #outerClothing: ClothingOuterHardsuitSyndie # goobstation - duke nukies
=======
    outerClothing: ClothingOuterHardsuitSyndieBiocode # Sunrise-Edit
>>>>>>> 7709d7a6a8 (Фикс биокода скафов)
    shoes: ClothingShoesBootsCombatFilled
    id: SyndiPDA
    pocket2: PlushieCarp
    belt: ClothingBeltMilitaryWebbing
  storage:
    back:
    - WeaponPistolViper
    - PinpointerSyndicateNuclear
    - DeathAcidifierImplanter

#Nuclear Operative Gear
- type: startingGear
  id: SyndicateOperativeGearFull
  parent: SyndicateOperativeGearFullNoUplink
  equipment:
    pocket2: BaseUplinkRadio225TC # Goobstation - Telecrystal rework

#Nuclear Operative Commander Gear
- type: startingGear
  id: SyndicateCommanderGearFull
  parent: SyndicateOperativeGearFullNoUplink
  equipment:
    neck: SyndicateWhistle
<<<<<<< HEAD
    pocket2: BaseUplinkRadio350TC # goobstation - im rich :fire::fire:
    #outerClothing: ClothingOuterHardsuitSyndieCommander # goobstation - duke nukies
=======
    outerClothing: ClothingOuterHardsuitSyndieCommanderBiocode # Sunrise-Edit
>>>>>>> 7709d7a6a8 (Фикс биокода скафов)
  inhand:
  - NukeOpsDeclarationOfWar

#Nuclear Operative Medic Gear
- type: startingGear
  id: SyndicateOperativeMedicFull
  parent: SyndicateOperativeGearFull
  equipment:
    eyes: ClothingEyesHudSyndicateAgent
<<<<<<< HEAD
    #outerClothing: ClothingOuterHardsuitSyndieMedic # goobstation - duke nukies
=======
    outerClothing: ClothingOuterHardsuitSyndieMedicBiocode # Sunrise-Edit
>>>>>>> 7709d7a6a8 (Фикс биокода скафов)
    shoes: ClothingShoesBootsMagSyndie
    id: SyndiAgentPDA
    belt: ClothingBeltMilitaryWebbingMedFilled
  storage:
    back:
    - SyndiHypo
    - SawAdvanced
    - Cautery
    - CombatKnife
    - WeaponPistolViper
    - PinpointerSyndicateNuclear
    - HandheldHealthAnalyzer
    - CombatMedipen
    - DeathAcidifierImplanter

#Lone Operative Gear
- type: startingGear
  id: SyndicateLoneOperativeGearFull
  parent: SyndicateOperativeGearFull
  equipment:
    # Goobstation - Telecrystal rework
    pocket2: BaseUplinkRadio350TC
